apiVersion: v1
kind: Pod
metadata:
  name: labels-annotations
  labels:
    description: lables_are-used.toidentifytheresourcesinsidek8susingselectors
    project: roboshop
    env: development
    other: allows_only-63.charswithnospecailcharacters
  annotations:
    description: annotations are used to identify the resources outside k8s and it allows upto 256 KB
    jenkins_web_url: "https://blah-blah"
spec:
  containers:
  - name: nginx
    image: almalinux:9

