apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-env
data:
  project: roboshop
  environment: development
  course: kubernetes

# Give reference to pod for better readability and dont use env as it looks clusmy if we have more like this. If you want to change anything in future just come here and change and restart pod etc..
