apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  labels:
    project: roboshop
data:
  username: YW1lZXIK # echo ameer | base 64 -> echo YW1lZXIK | base64 --decode
  password: YWRtaW4xMjMK

# K8s secrests are not really secrets as those are just encode values and anyone can decode easily. hence, use secretmanagers for this.
